---
version: "3.8"

services:
  app:
    image: "decentral1se/biobulkbende.org:latest"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - proxy
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.biobulkbende-org.loadbalancer.server.port=5000"
        - "traefik.http.routers.biobulkbende-org.rule=Host(`biobulkbende.org`)"
        - "traefik.http.routers.biobulkbende-org.entrypoints=web-secure"
        - "traefik.http.routers.biobulkbende-org.tls.certresolver=production"

networks:
  proxy:
    external: true
